version: 0.1

phases:
  install:
    commands:
      - npm install --prefix text-sort
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm test --prefix text-sort > build.log
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build.log